# CMake generated Testfile for 
# Source directory: /home/jhahn/sources/ecutools/src/aws_iot_src/external_libs/mbedTLS/tests
# Build directory: /home/jhahn/sources/ecutools/src/aws_iot_src/external_libs/mbedTLS/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(aes.ecb-suite "test_suite_aes.ecb")
ADD_TEST(aes.cbc-suite "test_suite_aes.cbc")
ADD_TEST(aes.cfb-suite "test_suite_aes.cfb")
ADD_TEST(aes.rest-suite "test_suite_aes.rest")
ADD_TEST(arc4-suite "test_suite_arc4")
ADD_TEST(asn1write-suite "test_suite_asn1write")
ADD_TEST(base64-suite "test_suite_base64")
ADD_TEST(blowfish-suite "test_suite_blowfish")
ADD_TEST(camellia-suite "test_suite_camellia")
ADD_TEST(ccm-suite "test_suite_ccm")
ADD_TEST(cipher.aes-suite "test_suite_cipher.aes")
ADD_TEST(cipher.arc4-suite "test_suite_cipher.arc4")
ADD_TEST(cipher.blowfish-suite "test_suite_cipher.blowfish")
ADD_TEST(cipher.camellia-suite "test_suite_cipher.camellia")
ADD_TEST(cipher.ccm-suite "test_suite_cipher.ccm")
ADD_TEST(cipher.des-suite "test_suite_cipher.des")
ADD_TEST(cipher.gcm-suite "test_suite_cipher.gcm")
ADD_TEST(cipher.null-suite "test_suite_cipher.null")
ADD_TEST(cipher.padding-suite "test_suite_cipher.padding")
ADD_TEST(ctr_drbg-suite "test_suite_ctr_drbg")
ADD_TEST(debug-suite "test_suite_debug")
ADD_TEST(des-suite "test_suite_des")
ADD_TEST(dhm-suite "test_suite_dhm")
ADD_TEST(ecp-suite "test_suite_ecp")
ADD_TEST(ecdh-suite "test_suite_ecdh")
ADD_TEST(ecdsa-suite "test_suite_ecdsa")
ADD_TEST(entropy-suite "test_suite_entropy")
ADD_TEST(error-suite "test_suite_error")
ADD_TEST(gcm.aes128_en-suite "test_suite_gcm.aes128_en")
ADD_TEST(gcm.aes192_en-suite "test_suite_gcm.aes192_en")
ADD_TEST(gcm.aes256_en-suite "test_suite_gcm.aes256_en")
ADD_TEST(gcm.aes128_de-suite "test_suite_gcm.aes128_de")
ADD_TEST(gcm.aes192_de-suite "test_suite_gcm.aes192_de")
ADD_TEST(gcm.aes256_de-suite "test_suite_gcm.aes256_de")
ADD_TEST(gcm.camellia-suite "test_suite_gcm.camellia")
ADD_TEST(hmac_drbg.misc-suite "test_suite_hmac_drbg.misc")
ADD_TEST(hmac_drbg.no_reseed-suite "test_suite_hmac_drbg.no_reseed")
ADD_TEST(hmac_drbg.nopr-suite "test_suite_hmac_drbg.nopr")
ADD_TEST(hmac_drbg.pr-suite "test_suite_hmac_drbg.pr")
ADD_TEST(md-suite "test_suite_md")
ADD_TEST(mdx-suite "test_suite_mdx")
ADD_TEST(memory_buffer_alloc-suite "test_suite_memory_buffer_alloc")
ADD_TEST(mpi-suite "test_suite_mpi")
ADD_TEST(pem-suite "test_suite_pem")
ADD_TEST(pkcs1_v21-suite "test_suite_pkcs1_v21")
ADD_TEST(pkcs5-suite "test_suite_pkcs5")
ADD_TEST(pk-suite "test_suite_pk")
ADD_TEST(pkparse-suite "test_suite_pkparse")
ADD_TEST(pkwrite-suite "test_suite_pkwrite")
ADD_TEST(shax-suite "test_suite_shax")
ADD_TEST(ssl-suite "test_suite_ssl")
ADD_TEST(rsa-suite "test_suite_rsa")
ADD_TEST(version-suite "test_suite_version")
ADD_TEST(xtea-suite "test_suite_xtea")
ADD_TEST(x509parse-suite "test_suite_x509parse")
ADD_TEST(x509write-suite "test_suite_x509write")
